stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python -V
- name: 流水线串联
  steps:
  - runScriptConfig:
      image: a/a:1
      shellScript: echo hello
timeout: 60
notification: {}
