stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: python -V
- name: 流水线串联
  steps:
  - runScriptConfig:
      image: zhaoming23/nginx:blue
      shellScript: echo hello
timeout: 60
notification: {}
